import React from 'react'

function TermsContent() {
  return (
    <div>
      <div className='mt-20 text-left px-16 text-sm'>
        <div className='text-4xl mb-10 font-semibold'>
            <h1>Terms & Conditions</h1>
        </div>
        <p className='mb-10'>Welcome to Baddhia, operated by Baddhia Limited (“us,” “our”, “we,” the “Company” or “Baddhia”).</p>
        <p className='font-semibold mb-2'>1. Acceptance of the Baddhia Terms of Service</p>
        <p className="leading-7 mb-10">By creating a Baddhia account or by using any Baddhia service, whether through a mobile or web application (collectively, the “Service” or “Platform”) you agree to be bound by (i) these Terms of Service, (ii) our Privacy Policy, (iii) any terms disclosed to you</p>
        <p className='leading-7 mb-9'> if you purchase or have purchased additional features, products, or services we offer on the Service (collectively, this “Agreement”). .If you do not accept and agree to be bound by all of the terms of this Agreement you should not use the Service.We may make changes to this Agreement and to the Service from time to time. We may do this for a variety of reasons including to reflect changes in or requirements of the law, new features, or changes in business practices. The most recent version of this Agreement will be posted on the Service under Settings and also on our website, and you should regularly check for the most recent version. The most recent version is the version that applies. If the changes include material changes to your rights or obligations, we will notify you in advance of the changes (unless we’re unable to do so under applicable law) by reasonable means, which could include notification through the Service or via email. If you continue to use the Service after the changes become effective, then you agree to the revised Agreement. You agree that this Agreement shall supersede any prior agreements (except as specifically stated herein), and shall govern your entire relationship with Baddhia, including but not limited to events, agreements, and conduct preceding your acceptance of this Agreement.</p>
        <p className='font-semibold mb-2'>2. Eligibility</p>
        <p className="leading-7 mb-10">You must be at least 18 years of age to create an account on Baddhia and use the Service. By creating an account and using the Service, you represent and warrant that:
        i. you can form a binding contract with Baddhia,
        ii. you are not a person who is barred from using the Service under the laws of the Federal Republic of Nigeria or any other applicable jurisdiction (for example, you do not appear on the U.S. Treasury Department’s list of Specially Designated Nationals or face any other similar prohibition),
        iii. you will comply with this Agreement and all applicable local, state, national and international laws, rules, and regulations, and
        iv. you have never been convicted of or pled no contest to a felony, a sex crime, or any crime involving violence, and that you are not required to register as a sex offender with any state, federal or local sex offender registry.</p>
        <p className='font-semibold mb-2'>3. Your Account</p>
        <p className="leading-7 mb-10">In order to use Baddhia, you may sign in using either your telephone number or email address. For more details regarding the information we collect from you and how we use it, please consult our Privacy Policy.You are responsible for maintaining the confidentiality of your login credentials you use to sign up for Baddhia, and you are solely responsible for all activities that occur under those credentials. If you think someone has gained access to your account, please contact us immediately.</p>
        <p className='font-semibold mb-2'>4. Modifying the Service and Termination</p>
        <p className="leading-7 mb-10">Baddhia is always striving to improve the Service and bring you additional features that you will find engaging and useful. This means we may add new product features or enhancements from time to time as well as remove some features, and if these actions do not materially affect your rights or obligations, we may not provide you with notice before taking them. We may even suspend the Service entirely, in which event we will notify you in advance unless exculpatory circumstances, such as safety or security concerns, prevent us from doing so.You may terminate your account at any time, for any reason, by following the instructions in “Settings” in the Service.Baddhia may terminate your account at any time without notice if it believes that you have violated this Agreement. Upon such termination, you will not be entitled to any refund for purchases. After your account is terminated, this Agreement will terminate, except that the following provisions will still apply to you and Baddhia: Section 4, Section 5, and Sections 12 - 19.</p>
        <p className='font-semibold mb-2'>5. Safety; Your Interactions with Other Members</p>
        <p className="leading-7 mb-10">Though Baddhia strives to encourage a respectful member experience through features like the “mutual likes” that allows members to be paired only after they have both indicated interest in one another, Baddhia is not responsible for the conduct of any member on or off the Service.i. You agree to use caution in all interactions with other members, particularly if you decide to communicate off the platform or meet in person. .ii. You agree that you will not provide your financial information (for example, your credit/debit card or bank account information), or otherwise send money to other members, except if you decide to share funds with them via your Baddhia main wallet or show appreciation for their gallery content.iii. You are solely responsible for your interactions with other members.iv. You understand that Baddhia does not conduct criminal background checks on its members or otherwise inquire into the background of its members. Baddhia makes no representations or warranties as to the conduct or compatibility of members. Baddhia reserves the right to conduct – and you authorize Baddhia to conduct – any criminal background check or other screenings (such as sex offender register searches) at any time using available public records obtained by it or with the assistance of a consumer protection reporting agency, and you agree that any information you provide may be used for that purpose.</p>
        <p className='font-semibold mb-2'>6. Rights Baddhia Grants You</p>
        <p className="leading-7 mb-10">Baddhia grants you a personal, worldwide, royalty-free, non-assignable, non-exclusive, revocable, and non-sublicensable license to access and use the Service. This license is for the sole purpose of letting you use and enjoy the Service’s benefits as intended by Baddhia and permitted by this Agreement. Therefore, you agree NOT to::<br></br>
        i. use the Service or any content contained in the Service for any commercial purposes without our written consent.<br></br>
        ii. copy, modify, transmit, create any derivative works from, make use of, or reproduce in any way any copyrighted material, images, trademarks, trade names, service marks, or other intellectual property, content, or proprietary information accessible through the Service without Baddhia’s prior written consent.<br></br>
        iii. express or imply that any statements you make are endorsed by Baddhia.<br></br>
        iv. use any robot, bot, spider, crawler, scraper, site search/retrieval application, proxy or other manual or automatic device, method, or process to access, retrieve, index, “data mine,” or in any way reproduce or circumvent the navigational structure or presentation of the Service or its contents<br></br>
        v. use the Service in any way that could interfere with, disrupt, or negatively affect the Service or the servers or networks connected to the Service.<br></br>
        vi. upload viruses or other malicious code or otherwise compromise the security of the Service.<br></br>
        vii. forge headers or otherwise manipulate identifiers in order to disguise the origin of any information transmitted to or through the Service.<br></br>
        viii. “frame” or “mirror” any part of the Service without Baddhia’s prior written authorization.<br></br>
        ix. use meta tags or code or other devices containing any reference to Baddhia or the Service (or any trademark, trade name, service mark, logo, or slogan of Baddhia) to direct any person to any other website for any purpose.<br></br>
        x. modify, adapt, sublicense, translate, sell, reverse engineer, decipher, decompile, or otherwise disassemble any portion of the Service, or cause others to do so.<br></br>
        xi. use or develop any third-party applications that interact with the Service or other members’ Content or information without our written consent.<br></br>
        xii. use, access, or publish the Baddhia application programming interface without our written consent.<br></br>
        xiii. probe, scan or test the vulnerability of our Service or any system or network.<br></br>
        xiv. encourage or promote any activity that violates this Agreement.<br></br>

        Baddhia may investigate and take any available legal action in response to illegal and/ or unauthorized uses of the Service, including termination of your account.

        Any software that we provide you may automatically download and install upgrades, updates, or other new features. You may be able to adjust these automatic downloads through your device’s settings.</p>
        <p className='font-semibold mb-2'>7. Rights you Grant Baddhia.</p>
        <p className="leading-7 mb-10">By creating an account, you grant to Baddhia a worldwide, transferable, sub-licensable, royalty-free, right and license to host, store, use, copy, display, reproduce, adapt, edit, publish, modify and distribute information you authorize us to access from third parties such as Facebook, Google, or Apple, as well as any information you post, upload, display or otherwise make available (collectively, “post”) on the Service or transmit to other members (collectively, “Content”).Baddhia’s license to your Content shall be non-exclusive, except that Baddhia’s license shall be exclusive with respect to derivative works created through use of the Service. For example, Baddhia would have an exclusive license to screenshots of the Service that include your Content. In addition, so that Baddhia can prevent the use of your Content outside of the Service, you authorize Baddhia to act on your behalf with respect to infringing uses of your Content taken from the Service by other members or third parties. This expressly includes the authority, but not the obligation, to send notices on your behalf if your Content is taken and used by third parties outside of the ServiceOur license to your Content is subject to your rights under applicable law (for example laws regarding personal data protection to the extent any Content contains personal information as defined by those laws) and is for the limited purpose of operating, developing, providing, and improving the Service and researching and developing new ones.<br></br>
        i. You agree that any Content you place or that you authorize us to place on the Service may be viewed by other members and may be viewed by any person visiting or participating in the Service (such as individuals who may receive shared Content from other Baddhia members).<br></br>
        ii. You agree that all information that you submit upon creation of your account, is accurate and truthful and you have the right to post the Content on the Service and grant the license to Baddhia above.<br></br>
        iii. You understand and agree that we may monitor or review any Content you post as part of the Service. We may delete any Content, in whole or in part, that in our sole judgment violates this Agreement or may harm the reputation of the Service.<br></br>
        iv. When communicating with our customer support personnel or any of our employees, directors, officers, or agents, you agree to be respectful and kind. If we feel that your behavior towards any of our representatives is at any time disrespectful, threatening, harassing, or offensive, we reserve the right to immediately terminate your account<br></br>
        v. In consideration for Baddhia allowing you to use the Service, you agree that we, our affiliates, and our third-party partners may place advertising materials on the Service.<br></br> 
        vi. By submitting suggestions or feedback to Baddhia regarding our Service, you agree that Baddhia may use and share such feedback for any purpose without compensating you.<br></br>
        vii. You agree that Baddhia may access, preserve and disclose your account information and Content if required to do so by law or in a good faith belief that such access, preservation or disclosure is reasonably necessary, such as to: (i) comply with legal process; (ii) enforce this Agreement; (iii) respond to claims that any Content violates the rights of third parties; (iv) respond to your requests for customer service; or (v) protect the rights, property or personal safety of the Company or any other person.</p>
        <p className='font-semibold mb-2'>8. Community Rules.</p>
        <p className="leading-7 mb-10">By using the Service, you agree that you will NOT:<br></br>
        i. use the Service for any purpose that is illegal or prohibited by this Agreement.<br></br>
        ii. use the Service for any harmful or nefarious purpose.<br></br>
        iii. use the Service in order to damage Baddhia.<br></br>
        iv . violate our Community Guidelines, as updated from time to time.<br></br>
        v. spam, solicit money from or defraud any members, except for voluntarily appreciations given to you by members.<br></br>
        vi. impersonate any person or entity or post any images of another person without his or her permission.<br></br>
        vii. bully, stalk, intimidate, assault, harass, mistreat, or defame any person.<br></br>
        viii. post any Content that violates or infringes anyone’s rights, including rights of publicity, privacy, copyright, trademark or other intellectual property or contract right.<br></br>
        ix. post any Content that is hate speech, threatening, sexually explicit or pornographic; incites violence; or contains nudity or graphic or gratuitous violence.<br></br>
        x. post any Content that promotes racism, bigotry, hatred, or physical harm of any kind against any group or individual.<br></br>
        xi. solicit passwords for any purpose, or personal identifying information for commercial or unlawful purposes from other users or disseminate another person’s personal information without his or her permission<br></br>
        xii. use another user’s account, share an account with another user, or maintain more than one account.<br></br>
        xiii. create another account if we have already terminated your account unless you have our permission.Baddhia reserves the right to investigate and/or terminate your account without a refund of any purchases if you have violated this Agreement, misused the Service, or behaved in a way that Baddhia regards as inappropriate or unlawful, including actions or communications that occur on or off the Service/Platform.</p>
        <p className='font-semibold mb-2'>9. Other Members’ Content</p>
        <p className="leading-7 mb-10">Although Baddhia reserves the right to review and remove Content that violates this Agreement, such Content is the sole responsibility of the member who posts it, and Baddhia cannot guarantee that all Content will comply with this Agreement. If you see Content on the Service that violates this Agreement, please report it within the Service or via support@baddhia.com.</p>
      
        <p className='font-semibold mb-2'>10. Purchases</p>
        <p className="leading-7 mb-10">All payments for purchases on the Baddhia platform will be initiated through the Baddhia main walletFrom time to time, Baddhia may offer products and services for purchase on the Baddhia online store through payment platforms authorized by Baddhia. If you choose to make an in-app purchase, you will be prompted to confirm your purchase with the applicable payment provider, and your method of payment (Baddhia main wallet) (your “Payment Method”) will be charged at the prices displayed to you for the service(s) you’ve selected as well as any sales or similar taxes that may be imposed on your payments, and you authorize Baddhia or the third party account, as applicable, to charge you.</p>
        <p className='font-semibold mb-2'>10.1 Subscription</p>
        <p className="leading-7 mb-10">You may choose to subscribe to any of Baddhia’s virtual products. When you do so, you agree to make payment through the Baddhia main wallet. After successful completion of your profile, you will be offered a 2-week free subscription to use the Service.Once your multimedia starter pack or recurrent subscription expires, you may decide to renew by funding your Baddhia main wallet and activating your subscription. Also, upon expiry, you will not be able to upload content in your gallery, chat, and share media files with any user except an exclusive partner.Deleting your account on Baddhia or deleting the Baddhia application from your device does not cancel your subscription; Baddhia will retain all funds charged to your Payment Method until your subscription expires. If you initiate a chargeback or otherwise reverse a payment made with your Payment Method, Baddhia may terminate your account immediately in its sole discretion.</p>
        <p className='font-semibold mb-2'>10.2 Display and CTA Emojis</p>
        <p className="leading-7 mb-6">From time to time, you may purchase a Display or CTA (Call-to-Action) emoji on the Baddhia online store. The Display emoji can be used while chatting with a user and can only be used once. Once it has been received by the recipient, you will no longer retain ownership of the emoji in your emoji library.</p>
        <p className="leading-7 mb-6">Before proceeding to purchase a CTA emoji, check if Baddhia has operational presence in your city or country. We do not advise that you purchase a CTA emoji on the Baddhia online store if Baddhia does not have an operational presence in your city or country. The CTA emoji requires the consent of the recipient before it can be activated. It must be activated within 72 hours of purchase, else the transaction will be cancelled, and payment reversed to your Baddhia main wallet. By purchasing the Display and CTA emoji, you acknowledge and agree that</p>
        <p className="leading-7 mb-6">i. the Baddhia online store is a platform for sellers to sell and buyers to purchase products,<br></br>
        ii. a contract for the sale and purchase of a product or products will come into force between you and the seller,<br></br>
        iii. Baddhia is not a party to the transaction between you and the seller, but shall accept binding sales on behalf of sellers,<br></br>
        iv. deliveries will be processed within 48 hours after the CTA emoji has been activated,<br></br>
        v. the seller is responsible for the safety and delivery lead time of products that you purchased on the Baddhia online store,<br></br>
        vi. the price of the product displayed in the product listing is genuine and acceptable to you,<br></br>
        vii. the price of the product will include all taxes, delivery charges, packaging charges, handling charges, administrative charges, insurance costs, and other ancillary costs and charges,<br></br>
        viii. Baddhia charges 5% commission on every product successfully delivered to you,ix. CTA emojis for services must be claimed within 7 days after successful activation.</p>
        
      </div>
    </div>
  )
}

export default TermsContent
